using CommonLibrary;

namespace ExportFactory.Shared
{
    public class EurocodeArtikelen
    {


        private readonly static Norm _nen1990 = new("EN1990", "Eurocode 0: Grondslagen van het constructief ontwerp");
        private readonly static Norm _nen1991 = new("EN1991", "Eurocode 1: Belastingen op constructies");
        private readonly static Norm _nen1992 = new("EN 1992", "Eurocode 2: Betonconstructies");

        public static List<EurocodeParagraaf> Paragraven =
        [
            // Hoofdstuk 1 - Algemeen
            new(_nen1992, "1", "Algemeen"),
            new(_nen1992, "1.1", "Onderwerp en toepassingsgebied"),
            new(_nen1992, "1.1.1", "Onderwerp en toepassingsgebied van Eurocode 2"),
            new(_nen1992, "1.1.2", "Onderwerp en toepassingsgebied van deel 1-1 van Eurocode 2"),
            new(_nen1992, "1.2", "Normatieve verwijzingen"),
            new(_nen1992, "1.2.1", "Algemene normen waarnaar is verwezen"),
            new(_nen1992, "1.2.2", "Overige normen waarnaar is verwezen"),
            new(_nen1992, "1.3", "Aannamen"),
            new(_nen1992, "1.4", "Onderscheid tussen beginselen en toepassingsregels"),
            new(_nen1992, "1.5", "Definities"),
            new(_nen1992, "1.5.1", "Algemeen"),
            new(_nen1992, "1.5.2", "Aanvullende termen en definities gebruikt in deze norm"),
            new(_nen1992, "1.6", "Symbolen"),

            // Hoofdstuk 2 - Grondslagen van het ontwerp en de berekening
            new(_nen1992, "2", "Grondslagen van het ontwerp en de berekening"),
            new(_nen1992, "2.1", "Eisen"),
            new(_nen1992, "2.1.1", "Basiseisen"),
            new(_nen1992, "2.1.2", "Beheersing van de betrouwbaarheid"),
            new(_nen1992, "2.1.3", "Ontwerplevensduur, duurzaamheid en kwaliteitsbeheer"),
            new(_nen1992, "2.2", "Beginselen van ontwerp en berekening op basis van grenstoestanden"),
            new(_nen1992, "2.3", "Basisvariabelen"),
            new(_nen1992, "2.3.1", "Belastingen en omgevingsinvloeden"),
            new(_nen1992, "2.3.1.1", "Algemeen"),
            new(_nen1992, "2.3.1.2", "Thermische effecten"),
            new(_nen1992, "2.3.1.3", "Ongelijkmatige zettingen/verplaatsingen"),
            new(_nen1992, "2.3.1.4", "Voorspanning"),
            new(_nen1992, "2.3.2", "Materiaal- en producteigenschappen"),
            new(_nen1992, "2.3.2.1", "Algemeen"),
            new(_nen1992, "2.3.2.2", "Krimp en kruip"),
            new(_nen1992, "2.3.3", "Vervormingen van beton"),
            new(_nen1992, "2.3.4", "Geometrische gegevens"),
            new(_nen1992, "2.3.4.1", "Algemeen"),
            new(_nen1992, "2.3.4.2", "Aanvullende eisen voor in-situ gestorte palen"),
            new(_nen1992, "2.4", "Toetsing door de methode van de partiële factoren"),
            new(_nen1992, "2.4.1", "Algemeen"),
            new(_nen1992, "2.4.2", "Rekenwaarden"),
            new(_nen1992, "2.4.2.1", "Partiële factor voor krimpeffecten"),
            new(_nen1992, "2.4.2.2", "Partiële factoren voor voorspanning"),
            new(_nen1992, "2.4.2.3", "Partiële factor voor vermoeiingsbelastingen"),
            new(_nen1992, "2.4.2.4", "Partiële factoren voor materialen"),
            new(_nen1992, "2.4.2.5", "Partiële factoren voor materialen voor funderingen"),
            new(_nen1992, "2.4.3", "Belastingscombinaties"),
            new(_nen1992, "2.4.4", "Toetsing van statisch evenwicht (EQU)"),
            new(_nen1992, "2.5", "Door proeven ondersteund ontwerpen"),
            new(_nen1992, "2.6", "Aanvullende eisen voor funderingen"),
            new(_nen1992, "2.7", "Eisen voor bevestigingsmiddelen"),

             // Hoofdstuk 3 - Materialen
            new(_nen1992, "3", "Materialen"),
            new(_nen1992, "3.1", "Beton"),
            new(_nen1992, "3.1.1", "Algemeen"),
            new(_nen1992, "3.1.2", "Sterkte"),
            new(_nen1992, "3.1.3", "Elastische vervorming"),
            new(_nen1992, "3.1.4", "Kruip en krimp"),
            new(_nen1992, "3.1.5", "Spanning-rekrelatie voor de niet-lineaire constructieve berekening"),
            new(_nen1992, "3.1.6", "Rekenwaarde van druk- en treksterktes"),
            new(_nen1992, "3.1.7", "Spanning-rekrelaties voor het berekenen van dwarsdoorsneden"),
            new(_nen1992, "3.1.8", "Buigtreksterkte"),
            new(_nen1992, "3.1.9", "Omsloten beton"),
            new(_nen1992, "3.2", "Betonstaal"),
            new(_nen1992, "3.2.1", "Algemeen"),
            new(_nen1992, "3.2.2", "Eigenschappen"),
            new(_nen1992, "3.2.3", "Sterkte"),
            new(_nen1992, "3.2.4", "Ductiliteitseigenschappen"),
            new(_nen1992, "3.2.5", "Lassen"),
            new(_nen1992, "3.2.6", "Vermoeiing"),
            new(_nen1992, "3.2.7", "Aannamen voor de berekening"),
            new(_nen1992, "3.3", "Voorspanstaal"),
            new(_nen1992, "3.3.1", "Algemeen"),
            new(_nen1992, "3.3.2", "Eigenschappen"),
            new(_nen1992, "3.3.3", "Sterkte"),
            new(_nen1992, "3.3.4", "Ductiliteitseigenschappen"),
            new(_nen1992, "3.3.5", "Vermoeiing"),
            new(_nen1992, "3.3.6", "Aannamen voor de berekening"),
            new(_nen1992, "3.3.7", "Voorspanelementen in omhullingen"),
            new(_nen1992, "3.4", "Voorspanmiddelen"),
            new(_nen1992, "3.4.1", "Verankeringen en koppelingen"),
            new(_nen1992, "3.4.1.1", "Algemeen"),
            new(_nen1992, "3.4.1.2", "Mechanische eigenschappen"),
            new(_nen1992, "3.4.2", "Uitwendige niet-hechtende spanelementen"),
            new(_nen1992, "3.4.2.1", "Algemeen"),
            new(_nen1992, "3.4.2.2", "Verankeringen"),

            // Hoofdstuk 4 - Duurzaamheid en dekking op de wapening
            new(_nen1992, "4", "Duurzaamheid en dekking op de wapening"),
            new(_nen1992, "4.1", "Algemeen"),
            new(_nen1992, "4.2", "Milieu-omstandigheden"),
            new(_nen1992, "4.3", "Duurzaamheideisen"),
            new(_nen1992, "4.4", "Toetsingsmethoden"),
            new(_nen1992, "4.4.1", "Betondekking"),
            new(_nen1992, "4.4.1.1", "Algemeen"),
            new(_nen1992, "4.4.1.2", "Minimale dekking, cmin"),
            new(_nen1992, "4.4.1.3", "Toeslag in het ontwerp voor uitvoeringstoleranties"),

            // Hoofdstuk 5 - Constructieve berekening
            new(_nen1992, "5", "Constructieve berekening"),
            new(_nen1992, "5.1", "Algemeen"),
            new(_nen1992, "5.1.1", "Algemene eisen"),
            new(_nen1992, "5.1.2", "Specifieke eisen voor funderingen"),
            new(_nen1992, "5.1.3", "Belastingsgevallen en -combinaties"),
            new(_nen1992, "5.1.4", "Tweede-orde-effecten"),
            new(_nen1992, "5.2", "Geometrische imperfecties"),
            new(_nen1992, "5.3", "Schematisering van de constructie"),
            new(_nen1992, "5.3.1", "Constructieve modellen voor de algemene berekening"),
            new(_nen1992, "5.3.2", "Geometrische gegevens"),
            new(_nen1992, "5.3.2.1", "Meewerkende flensbreedte (alle grenstoestanden)"),
            new(_nen1992, "5.3.2.2", "Effectieve overspanning van liggers en platen in gebouwen"),
            new(_nen1992, "5.4", "Lineair-elastische berekening"),
            new(_nen1992, "5.5", "Lineair-elastische berekening met beperkte herverdeling"),
            new(_nen1992, "5.6", "Plastische berekening"),
            new(_nen1992, "5.6.1", "Algemeen"),
            new(_nen1992, "5.6.2", "Plastische berekening van balken, raamwerken en platen"),
            new(_nen1992, "5.6.3", "Rotatiecapaciteit"),
            new(_nen1992, "5.6.4", "Berekening met staafwerkmodellen"),

            // Hoofdstuk 6 - Uiterste grenstoestanden (UGT)
            new(_nen1992, "6", "Uiterste grenstoestanden (UGT)"),
            new(_nen1992, "6.1", "Buiging met of zonder normaalkracht"),
            new(_nen1992, "6.2", "Dwarskracht"),
            new(_nen1992, "6.2.1", "Algemene toetsingsprocedure"),
            new(_nen1992, "6.2.2", "Elementen die geen berekende dwarskrachtwapening vereisen"),
            new(_nen1992, "6.2.3", "Elementen die berekende dwarskrachtwapening vereisen"),
            new(_nen1992, "6.2.4", "Afschuiving tussen lijfplaat en flenzen"),
            new(_nen1992, "6.2.5", "Afschuiving in het aansluitvlak tussen op verschillende tijdstippen gestort beton"),
            new(_nen1992, "6.3", "Wringing"),
            new(_nen1992, "6.3.1", "Algemeen"),
            new(_nen1992, "6.3.2", "Ontwerpprocedure"),
            new(_nen1992, "6.3.3", "Wringing met belemmerde welving"),
            new(_nen1992, "6.4", "Pons"),
            new(_nen1992, "6.4.1", "Algemeen"),
            new(_nen1992, "6.4.2", "Belastingsverdeling en eerste controle-omtrek"),
            new(_nen1992, "6.4.3", "Ponsberekening"),
            new(_nen1992, "6.4.4", "Ponsweerstand van platen en kolomvoeten zonder ponswapening"),
            new(_nen1992, "6.4.5", "Ponsweerstand van platen en kolomvoeten met ponswapening"),
            new(_nen1992, "6.5", "Berekening met behulp van staafwerkmodellen"),
            new(_nen1992, "6.5.1", "Algemeen"),
            new(_nen1992, "6.5.2", "Drukstaven"),
            new(_nen1992, "6.5.3", "Trekstaven"),
            new(_nen1992, "6.5.4", "Knopen"),
            new(_nen1992, "6.6", "Verankeringen en overlappinglassen"),
            new(_nen1992, "6.7", "Gedeeltelijk belaste gebieden"),
            new(_nen1992, "6.8", "Vermoeiing"),
            new(_nen1992, "6.8.1", "Toetsingsvoorwaarden"),
            new(_nen1992, "6.8.2", "Snedekrachten en spanningen bij toetsing op vermoeiing"),
            new(_nen1992, "6.8.3", "Belastingscombinaties"),
            new(_nen1992, "6.8.4", "Toetingsprocedure voor beton- en voorspanstaal"),
            new(_nen1992, "6.8.5", "Toetsing door een schade-equivalent spanningsbereik"),
            new(_nen1992, "6.8.6", "Andere toetsingen"),
            new(_nen1992, "6.8.7", "Toetsing van beton onder druk of afschuiving"),

            // Hoofdstuk 7 - Bruikbaarheidsgrenstoestanden (BGT)
            new(_nen1992, "7", "Bruikbaarheidsgrenstoestanden (BGT)"),
            new(_nen1992, "7.1", "Algemeen"),
            new(_nen1992, "7.2", "Spanningsbeperking"),
            new(_nen1992, "7.3", "Scheurbeheersing"),
            new(_nen1992, "7.3.1", "Algemene beschouwingen"),
            new(_nen1992, "7.3.2", "Oppervlaktes van de minimumwapening"),
            new(_nen1992, "7.3.3", "Scheurbeheersing zonder directe berekening"),
            new(_nen1992, "7.3.4", "Berekening van scheurwijdtes"),
            new(_nen1992, "7.4", "Doorbuigingscontrole"),
            new(_nen1992, "7.4.1", "Algemene beschouwingen"),
            new(_nen1992, "7.4.2", "Gevallen waarin berekeningen achterwege mogen blijven"),
            new(_nen1992, "7.4.3", "Controleren van doorbuigingen door berekening"),

            // Hoofdstuk 8 - Detailleren van wapening en voorspanelementen
            new(_nen1992, "8", "Detailleren van wapening en voorspanelementen – Algemeen"),
            new(_nen1992, "8.1", "Algemeen"),
            new(_nen1992, "8.2", "Staafafstanden"),
            new(_nen1992, "8.3", "Toelaatbare doorndiameters voor gebogen staven"),
            new(_nen1992, "8.4", "Verankering van langswapening"),
            new(_nen1992, "8.4.1", "Algemeen"),
            new(_nen1992, "8.4.2", "Uiterst opneembare aanhechtspanning"),
            new(_nen1992, "8.4.3", "Basisverankeringslengte"),
            new(_nen1992, "8.4.4", "Rekenwaarde van de verankeringslengte"),
            new(_nen1992, "8.5", "Verankering van beugels en dwarskrachtwapening"),
            new(_nen1992, "8.6", "Verankering door aangelaste staven"),
            new(_nen1992, "8.7", "Overlappingen en mechanische koppelingen"),
            new(_nen1992, "8.7.1", "Algemeen"),
            new(_nen1992, "8.7.2", "Overlappingen"),
            new(_nen1992, "8.7.3", "Overlappingslengte"),
            new(_nen1992, "8.7.4", "Dwarswapening in het overlappingsgebied"),
            new(_nen1992, "8.7.5", "Overlappingen voor gepuntlaste wapeningsnetten"),
            new(_nen1992, "8.8", "Aanvullende regels voor staven met grote diameter"),
            new(_nen1992, "8.9", "Gebundelde staven"),
            new(_nen1992, "8.10", "Voorspanelementen"),

            // Hoofdstuk 9 - Detailleren van elementen en specifieke regels
            new(_nen1992, "9", "Detailleren van elementen en specifieke regels"),
            new(_nen1992, "9.1", "Algemeen"),
            new(_nen1992, "9.2", "Balken"),
            new(_nen1992, "9.2.1", "Langswapening"),
            new(_nen1992, "9.2.2", "Dwarskrachtwapening"),
            new(_nen1992, "9.2.3", "Wringwapening"),
            new(_nen1992, "9.2.4", "Huidwapening"),
            new(_nen1992, "9.3", "Massieve platen"),
            new(_nen1992, "9.4", "Vlakke plaatvloeren"),
            new(_nen1992, "9.5", "Kolommen"),
            new(_nen1992, "9.6", "Wanden"),
            new(_nen1992, "9.7", "Gedrongen liggers"),
            new(_nen1992, "9.8", "Funderingen"),
            new(_nen1992, "9.9", "Gebieden met discontinuïteit in geometrie of belasting"),
            new(_nen1992, "9.10", "Trekbanden"),


        ];





    }
}
