<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kaskon.Algemeen" Version="1.0.0" />
    <PackageReference Include="Kaskon.BetonProfielen" Version="1.0.0" />
    <PackageReference Include="Kaskon.ParametrischeProfielen" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.3" />
    <PackageReference Include="MigraDoc.DocumentObjectModel.Core" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Libs\" />
  </ItemGroup>

</Project>
