<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\downloadFile.js" />
    <Content Remove="wwwroot\js\downloadFileFromStream.js" />
  </ItemGroup>


	
	
	
  <ItemGroup>
    <Content Include="App.razor.BAK" />
    <Content Include="Routes.razor.BAK" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Kaskon.Algemeen" Version="1.0.0" />
	  <PackageReference Include="Kaskon.BetonProfielen" Version="1.1.500" />
	  <PackageReference Include="Kaskon.ParametrischeProfielen" Version="1.0.2" />
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.12.0" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.12.0" />
    <PackageReference Include="Plotly.Blazor" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Beton\Buiging\Examples\Beton\" />
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\downloadFile.js" />
    <None Include="wwwroot\js\downloadFileFromStream.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CommonLibrary\CommonLibrary.csproj" />
    <ProjectReference Include="..\..\Eurocode0.Grondslagen\Eurocode0.Grondslagen.csproj" />
    <ProjectReference Include="..\..\Eurocode1.Belastingen\Eurocode1.Belastingen.csproj" />
    <ProjectReference Include="..\..\Eurocode2.BetonConstructies\Eurocode2.BetonConstructies.csproj" />
    <ProjectReference Include="..\..\Eurocode3.StaalConstructies\Eurocode3.StaalConstructies.csproj" />
    <ProjectReference Include="..\..\Eurocode4.StaalBetonConstructies\Eurocode4.StaalBetonConstructies.csproj" />
    <ProjectReference Include="..\..\Eurocode5.HoutConstructies\Eurocode5.HoutConstructies.csproj" />
    <ProjectReference Include="..\..\Eurocode6.Metselwerk\Eurocode6.Metselwerk.csproj" />
    <ProjectReference Include="..\..\Eurocode7.Geotechniek\Eurocode7.Geotechniek.csproj" />
    <ProjectReference Include="..\..\Eurocode8.Aardbevingen\Eurocode8.Aardbevingen.csproj" />
    <ProjectReference Include="..\..\EurocodeRazorClassLibrary\EurocodeRazorClassLibrary.csproj" />
    <ProjectReference Include="..\..\ExportFactory\ExportFactory.csproj" />
    <ProjectReference Include="..\Eurocode.Blazor.Demo.Generators\Generators\Generators.csproj" />
  </ItemGroup>
</Project>
