<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Eurocode.Grondslagen</RootNamespace>

	<!-- NuGet-package instellingen -->
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>Kaskon.Eurocode0.Grondslagen</PackageId>
	<Version>1.0.0</Version>
	<Authors>Bart van der Linden</Authors>
	<Company>Kaskon</Company>
	<Description>Eurocode 0.</Description>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/YourRepo</RepositoryUrl>
	<PackageProjectUrl>https://www.yourprojectsite.com</PackageProjectUrl>

	<!-- Lokale map voor .nupkg -->
	<PackageOutputPath>T:\04 Standaarden\NuGetPackages</PackageOutputPath>
	<Copyright>Copyright © 2025 Kaskon</Copyright>
	<PackageTags>Kaskon;Blazor;FluentUI;Eurocode;Grondslagen</PackageTags>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  
	  
	  
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExportFactory\ExportFactory.csproj" />
  </ItemGroup>
</Project>