<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Eurocode.BetonConstructies</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Eurocode0.Grondslagen\Eurocode0.Grondslagen.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BetonProfielen">
      <HintPath>..\..\Profielen\BetonProfielen\bin\Debug\net9.0\BetonProfielen.dll</HintPath>
    </Reference>
    <Reference Include="Kaskon_it.Algemeen">
      <HintPath>..\..\Profielen\BetonProfielen\bin\Debug\net9.0\Kaskon_it.Algemeen.dll</HintPath>
    </Reference>
    <Reference Include="ParametrischeProfielen">
      <HintPath>..\..\Profielen\BetonProfielen\bin\Debug\net9.0\ParametrischeProfielen.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="NewFolder2\" />
  </ItemGroup>
</Project>