<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Eurocode.BetonConstructies</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Kaskon.Algemeen" Version="1.0.0" />
    <PackageReference Include="Kaskon.BetonProfielen" Version="1.0.0" />
    <PackageReference Include="Kaskon.ParametrischeProfielen" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Eurocode0.Grondslagen\Eurocode0.Grondslagen.csproj" />
  </ItemGroup>


	
	
	
</Project>