<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Eurocode.BetonConstructies</RootNamespace>
	
	<!-- NuGet-package instellingen -->
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>Kaskon.Eurocode2.BetonConstructies</PackageId>
	<Version>6.1.3</Version>
	<Authors>Bart van der Linden</Authors>
	<Company>Kaskon</Company>
	<Description>Eurocode 2 Betonconstructies</Description>

	  <PackageLicenseFile>license.md</PackageLicenseFile>
	  <PackageReadmeFile>readme.md</PackageReadmeFile>
	  <PackageIcon>kaskon.png</PackageIcon>

	<!-- Lokale map voor .nupkg -->
	<PackageOutputPath>T:\04 Standaarden\NuGetPackages</PackageOutputPath>
	<Copyright>Copyright © 2026 Kaskon</Copyright>
	<PackageTags>Kaskon;Blazor;FluentUI;Eurocode;EC2;Betonconstructies;Beton</PackageTags>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  
	  
  </PropertyGroup>

	<ItemGroup>
		<None Include="Icons/kaskon.png" Pack="true" PackagePath="/" />
		<None Include="Docs/license.md" Pack="true" PackagePath="/" />
		<None Include="Docs/readme.md" Pack="true" PackagePath="/" />
	</ItemGroup>
	
	
  <ItemGroup>
    <PackageReference Include="Kaskon.Algemeen" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
	<Using Include="CommonLibrary.Modelling" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="..\CommonLibrary\CommonLibrary.csproj" />
	<ProjectReference Include="..\..\Profielen\BetonProfielen\BetonProfielen.csproj" />
    <ProjectReference Include="..\..\Profielen\ParametrischeProfielen\ParametrischeProfielen.csproj" />
    <ProjectReference Include="..\Eurocode0.Grondslagen\Eurocode0.Grondslagen.csproj" />
    <ProjectReference Include="..\Eurocode1.Belastingen\Eurocode1.Belastingen.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Docs\license.md">
      <PackagePath>/</PackagePath>
      <Pack>true</Pack>
    </None>
    <None Update="Docs\readme.md">
      <PackagePath>/</PackagePath>
      <Pack>true</Pack>
    </None>
    <None Update="Icons\kaskon.png">
      <PackagePath>/</PackagePath>
      <Pack>true</Pack>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Algemeen\" />
  </ItemGroup>


	
	
	
</Project>